application: doumail-backup
version: 2
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico
  expiration: "30d"

- url: /static
  static_dir: static
  expiration: "30d"
  
- url: /.*
  script: app.py

builtins:
- datastore_admin: on